config/routes.rb
Rails.application.routes.draw do
  resources :person
  root :to => 'persons#index'
  get 'person/index'
  get 'person/delete'

end

app/models/attestate.rb
class Attestate < ActiveRecord::Base
  has_many :persons
end

app/models/person.rb
class Person < ActiveRecord::Base
  belongs_to :attestate

  def self.search(par)
    if par[:search]
      if par[:lvl1] == ''
        par[:lvl1] = 0
      end
      if par[:lvl2] == ''
        par[:lvl2] = 10000
      end

      #par[:lvl2] ||= '0'
      x=where('name LIKE ?', "%#{par[:search]}%")
      x=x.where('wmid LIKE ?', "%#{par[:wmid]}%")
      x=x.where('lvl >= ?', par[:lvl1])
      x=x.where('lvl <= ?', par[:lvl2])
      if par[:att]!='0'
        x=x.where('attestate_id = ?', par[:att])
      end

      return x
    else
      default_scoped
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/person_controller.rb
class PersonController < ApplicationController
  helper_method :sort_column, :sort_direction, :parse_wmid

  def index
     params[:sort] ||= 'name'
    # Проверка надо ли добавить wmid или кошелёк
    if params[:new]!=nil and params[:new].size==12
      parse_wmid('<request><wmid>' + params[:new] + '</wmid></request>')
      params[:new]=nil
    elsif params[:new]!=nil and params[:new].size==13
      parse_wmid('<request><purse>' + params[:new] + '</purse></request>')
    end

    @persons = Person.search(params).order(sort_column + ' ' + sort_direction).paginate(per_page: 8, page: params[:page])
    @att=Attestate.all

  end

  def destroy
    Person.find(params[:id]).destroy
    redirect_to :action => 'index'
  end




  private
    def parse_wmid(z)

    res=RestClient.post 'https://passport.webmoney.ru/xml/XMLGetWMIDInfo.aspx', z
    xm = Nokogiri::XML(res)

    if xm.root.at_xpath('error')!=nil
      return
    end
    att=xm.root.at_xpath('certinfo/attestat/row')['typename']
    @test=xm.root.at_xpath('certinfo/attestat/row')['typename']

    if Attestate.where('attname LIKE ?', "%#{att}%").empty?
       Attestate.create(attname: att)
    end

    x=Attestate.where('attname LIKE ?', "%#{att}%")
    attestate_id=x.first.id
    wmid=xm.root.at_xpath('certinfo/wmids/row')['wmid']
    lvl=xm.root.at_xpath('certinfo/wmids/row')['level']
    date= xm.root.at_xpath('certinfo/wmids/row')['datereg']
    name =xm.root.at_xpath('certinfo/userinfo/value/row')['fname'] + ' ' + xm.root.at_xpath('certinfo/userinfo/value/row')['iname'] + ' ' + xm.root.at_xpath('certinfo/userinfo/value/row')['oname']
    review= xm.root.at_xpath('certinfo/claims/row')['posclaimscount'] + '/' + xm.root.at_xpath('certinfo/claims/row')['negclaimscount']
    rdate= xm.root.at_xpath('certinfo/claims/row')['claimslastdate']
    Person.create(wmid: wmid,attestate_id: attestate_id, lvl: lvl, date:date, name: name, review:review, rdate:rdate)

    end
  def sort_column
    Person.column_names.include?(params[:sort])? params[:sort] : 'name'

  end
  def sort_direction
    %w[asc desc].include?(params[:direction])? params[:direction] : 'asc'

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title=nil)
    title ||=column.titleize
    direction = column == sort_column && sort_direction=='asc' ? 'desc' : 'asc'
    link_to title, params.merge(sort: column, direction: direction, page: nil)

  end

end

app/helpers/person_helper.rb
module PersonHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Asd</title>

  <%= javascript_include_tag :application %>
  <%= stylesheet_link_tag    'application', media: 'all'%>
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
  <%= csrf_meta_tags %>




</head>
<body>
<div class="container-fluid">


<%= yield %>
</div>
</body>
</html>

app/views/person/_persons.html.erb
<table class="table  table-striped table-hover table-condensed">
  <tr class="info">

    <th><%= sortable 'wmid', 'WMID' %></th>
    <th><%= sortable 'name', 'Имя' %></th>
    <th><%= sortable 'lvl', 'Бизнес уровень' %></th>
    <th><%= sortable 'date', 'Дата регистрации'%></th>
    <th><%= sortable 'att', 'Аттестат'%></th>
    <th><%= sortable 'review', 'Отзывы'%></th>
    <th></th>
  </tr>
  <% @persons.each do |p| %>
      <tr id="<%=p.id %>">

        <td> <%= p.wmid %></td>
        <td> <%= p.name %></td>
        <td> <%= p.lvl %></td>
        <td> <%= Russian::strftime(p.date , '%d %B %Y')%></td>
        <td class="text-capitalize"><a id="<%= p.attestate_id %>" class="att"><%=p.attestate.attname%></a></td>
        <% if p.review=='0/0' %>
            <td><%= p.review %></td>
        <% else %>
            <td ><a class="tip"> <%= p.review %><span class="classic"><%= Russian::strftime(p.rdate , '%d %B %Y') %></span></a></td>
        <%end%>
        <td><%= link_to 'Удалить', person_path(p), method: :delete, remote:true, class:'del' %></td>


      </tr>
  <%end%>
</table>
<%= will_paginate @persons%>

app/views/person/index.html.erb
<br><br>

<%= form_tag person_index_path,class: 'form-inline', role: 'form', remote: true, method: 'get', id: 'persons_search' do %>
    <%= hidden_field_tag :direction, params[:direction]%>
    <%= hidden_field_tag :sort, params[:sort] %>
    <div class="form-group">
      <label>Имя</label><br>

      <%= text_field_tag :search, params[:search], class:'form-control' %>
    </div>
    <div class="form-group">
      <label>WMID</label><br>
      <%= text_field_tag :wmid, params[:wmid], class:'form-control'  %>
    </div>
    <div class="form-group">
      <label>Бизнес уровень</label><br>
      <%= text_field_tag :lvl1, params[:lvl1], class:'form-control', style: 'width  :70px'  %>
      <%= text_field_tag :lvl2, params[:lvl2], class:'form-control', style: 'width  :70px'  %>
    </div>
    <div class="form-group">
      <label>Тип аттестата</label><br>
      <select name="att" id="att" class="form-control"%>">
        <option value="0">Все аттестаты</option>
        <% @att.each do |a| %>
            <option value="<%= a.id %>"><%= a.attname %></option>
        <%end%>
      </select>
    </div>
    <div class="form-group"><br>
      <span class="glyphicon glyphicon-search"></span>
      <%= submit_tag 'Поиск', name: nil, class: 'btn btn-default' %>
    </div>


<% end %>
<p>
<%= form_tag person_index_path, class: 'form-inline', role: 'form', remote: true, method:'get', id: 'persons_new' do %>
      <label>WMID или Кошелёк</label><br>
      <%= text_field_tag :new, nil , class: 'form-control'  %>
    <%= submit_tag 'Добавить', name: nil, class: 'btn btn-default', id:'new_button'  %>
<% end %>
<br>



<div id="persons"><%=render 'persons'%></div>

app/views/person/index.js.erb
$("#persons").html("<%= escape_javascript(render('persons'))%>")